#!/usr/bin/env bash

chown ovs:ovs /opt/OpenvStorage/scripts/healthcheck.sh
chmod 755 /opt/OpenvStorage/scripts/healthcheck.sh
chmod +x /opt/OpenvStorage/scripts/healthcheck.sh

chown ovs:ovs /opt/OpenvStorage/scripts/healthcheck_cli.py
chmod 755 /opt/OpenvStorage/scripts/healthcheck_cli.py
chmod +x /opt/OpenvStorage/scripts/healthcheck_cli.py

# Clear the cache
python -c "from ovs.extensions.healthcheck.expose_to_cli import HealthCheckCLI; HealthCheckCLI.clear_cache()"